// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-2',
    aws_cognito_identity_pool_id: 'us-east-2:44d60e39-178f-4394-bec6-184af5eddb5a',
    aws_cognito_region: 'us-east-2',
    aws_user_pools_id: 'us-east-2_MncmyfGQC',
    aws_user_pools_web_client_id: '2ml4t1vfsjppeippf8knjf6jr0',
    oauth: {},
  };
  
  
  export default awsmobile;